[versions]
androidGradlePlugin = "8.3.1"
androidLibraryPlugin = "8.3.2"
kspPlugin = "1.9.23-1.0.20"
kotlinAndroidPlugin = "1.9.22"
hiltAndroidGradlePlugin = "2.51.1"
androidxComposeCompiler = "1.5.8"
hiltNavigationCompose = "1.2.0"
ktx = "1.13.1"
androidXAppCompat = "1.6.1"
junit = "4.13.2"
testExt = "1.1.5"
espressoCore = "3.5.1"
lifecycle = "2.8.1"
room = "2.6.1"
hilt = "2.51.1"
composeBom = "2024.05.00"
navigationCompose = "2.7.7"
constraintlayoutCompose = "1.1.0-alpha13"
coroutines = "1.8.1"
fallery = "1.0.4"
glide = "4.16.0"
landscapistGlide = "2.3.6"
moshiKotlin = "1.15.1"
processPhoenix = "3.0.0"
exoplayer = "1.3.1"
mockk = "1.13.10"
turbine = "1.1.0"
splashscreen = "1.0.1"
documentfile = "1.0.1"
material = "1.12.0"


[libraries]
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXAppCompat" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
testExt = { group = "androidx.test.ext", name = "junit", version.ref = "testExt" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
lifecycleViewModeKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycleCompiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "lifecycle" }
androidx-lifecycle-viewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
composeActivity = { group = "androidx.activity", name = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

androidx-constraintLayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
coroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
fallery = { group = "com.github.mehdiyari", name = "Fallery", version.ref = "fallery" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glideCompiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
landscapistGlide = { group = "com.github.skydoves", name = "landscapist-glide", version.ref = "landscapistGlide" }
moshiKotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
processPhoenix = { group = "com.jakewharton", name = "process-phoenix", version.ref = "processPhoenix" }
exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoplayer" }
media3UI = { group = "androidx.media3", name = "media3-ui", version.ref = "exoplayer" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
hiltAndroidGradleClassPath = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinAndroidPlugin" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibraryPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugin" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }